server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    set $app_version "${APP_VERSION}";

    location = /health {
        default_type application/json;
        if ($app_version = "v2") {
            return 500 '{"status":"error","version":"v2"}';
        }
        return 200 '{"status":"ok","version":"${APP_VERSION}"}';
        
    }

    location / {
        if ($app_version = "v2") {
            return 500;
        }
        try_files $uri $uri/ /index.html;
    }
}
